language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install codecov

# command to run tests
script:
  - python -m unittest buggyTriangles-2
  - coverage run buggyTriangles-2.py

after_success:
  - codecov

