language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install codecov

# command to run tests
script:
  - python -m unittest TestTriangle
  - coverage run --source=Triangle TestTriangle.py

after_success:
  - codecov

